/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReclamacoesRouteImport } from './routes/reclamacoes'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NovaRouteImport } from './routes/nova'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReclamacaoIdRouteImport } from './routes/reclamacao.$id'

const ReclamacoesRoute = ReclamacoesRouteImport.update({
  id: '/reclamacoes',
  path: '/reclamacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaRoute = NovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReclamacaoIdRoute = ReclamacaoIdRouteImport.update({
  id: '/reclamacao/$id',
  path: '/reclamacao/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nova': typeof NovaRoute
  '/portal': typeof PortalRoute
  '/reclamacoes': typeof ReclamacoesRoute
  '/reclamacao/$id': typeof ReclamacaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nova': typeof NovaRoute
  '/portal': typeof PortalRoute
  '/reclamacoes': typeof ReclamacoesRoute
  '/reclamacao/$id': typeof ReclamacaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nova': typeof NovaRoute
  '/portal': typeof PortalRoute
  '/reclamacoes': typeof ReclamacoesRoute
  '/reclamacao/$id': typeof ReclamacaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nova' | '/portal' | '/reclamacoes' | '/reclamacao/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nova' | '/portal' | '/reclamacoes' | '/reclamacao/$id'
  id:
    | '__root__'
    | '/'
    | '/nova'
    | '/portal'
    | '/reclamacoes'
    | '/reclamacao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NovaRoute: typeof NovaRoute
  PortalRoute: typeof PortalRoute
  ReclamacoesRoute: typeof ReclamacoesRoute
  ReclamacaoIdRoute: typeof ReclamacaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reclamacoes': {
      id: '/reclamacoes'
      path: '/reclamacoes'
      fullPath: '/reclamacoes'
      preLoaderRoute: typeof ReclamacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova': {
      id: '/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof NovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reclamacao/$id': {
      id: '/reclamacao/$id'
      path: '/reclamacao/$id'
      fullPath: '/reclamacao/$id'
      preLoaderRoute: typeof ReclamacaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NovaRoute: NovaRoute,
  PortalRoute: PortalRoute,
  ReclamacoesRoute: ReclamacoesRoute,
  ReclamacaoIdRoute: ReclamacaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
